name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.DOC_UPDATE }}
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        continue-on-error: true

      - name: Remove Old Wiki Content
        run: |
          echo "Removing old wiki content..."
          rm -rf wiki/*

      - name: Copy Files to Wiki
        run: |
          echo "Copying files..."
          cp -r docs/* wiki/
          ls -la wiki  # List files to verify copying

      - name: Set Introduction.md as the Landing Page
        run: |
          echo "Setting Introduction.md as the landing page..."
          mv wiki/Introduction.md wiki/Home.md
          ls -la wiki  # List files to verify changes

      - name: Create Custom Sidebar
        run: |
          echo "Creating custom sidebar..."
          echo "* [Home](Home.md)" > wiki/_Sidebar.md
          echo "* [Solution Architecture](Solution_Architecture.md)" >> wiki/_Sidebar.md
          echo "* [Configurations](Configurations.md)" >> wiki/_Sidebar.md
          echo "* [Explanation](Explanation.md)" >> wiki/_Sidebar.md
          echo "* [SETUP and Installation](SETUP-and-Installation.md)" >> wiki/_Sidebar.md
          echo "* [FAQ](FAQ.md)" >> wiki/_Sidebar.md
          cat wiki/_Sidebar.md  # Output the updated _Sidebar.md

      - name: Commit and Push Changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki content with custom sidebar" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: List files in wiki directory after push
        run: ls -la wiki
