name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        continue-on-error: true

      - name: Remove Old Wiki Content
        run: |
          echo "Removing old wiki content..."
          rm -rf wiki/*

      - name: Copy Files to Wiki
        run: |
          echo "Copying files..."
          cp -r docs/* wiki/
          ls -la wiki  # List files to verify copying

      - name: Create or Update _Sidebar.md
        run: |
          echo "Creating or updating _Sidebar.md..."
          echo "# Sidebar" > wiki/_Sidebar.md
          echo "* [Home](Introduction.md)" >> wiki/_Sidebar.md
          cat wiki/_Sidebar.md  # Output the updated _Sidebar.md

      - name: Commit and Push Changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki sidebar with link to Introduction.md" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: List files in wiki directory after push
        run: ls -la wiki
