name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.DOC_UPDATE }}
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        continue-on-error: true

      - name: Remove Old Wiki Content
        run: |
          echo "Removing old wiki content..."
          rm -rf wiki/*

      - name: Copy Files to Wiki
        run: |
          echo "Copying files..."
          cp -r docs/* wiki/
          ls -la wiki  # List files to verify copying

      - name: Rename Files for Desired Order
        run: |
          echo "Renaming files to achieve desired order..."
          mv wiki/Introduction.md wiki/_Home.md
          mv wiki/Solution_Architecture.md wiki/_Solution_Architecture.md
          mv wiki/Configurations.md wiki/_Configurations.md
          mv wiki/Explanation.md wiki/_Explanation.md
          mv wiki/SETUP-and-Installation.md wiki/_SETUP_and_Installation.md
          mv wiki/FAQ.md wiki/_FAQ.md
          ls -la wiki  # List files to verify changes

      - name: Commit and Push Changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki content with ordered filenames" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: List files in wiki directory after push
        run: ls -la wiki
