name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone Wiki Repository
        env:
          GITHUB_TOKEN: ${{ secrets.DOC_UPDATE }}
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki
        continue-on-error: true

      - name: Remove Old Wiki Content
        run: |
          echo "Removing old wiki content..."
          rm -rf wiki/*

      - name: Copy Files to Wiki
        run: |
          echo "Copying files..."
          cp -r docs/* wiki/
          ls -la wiki  # List files to verify copying

      - name: Rename Files to Ensure Correct Order
        run: |
          echo "Renaming files to ensure correct order..."
          mv wiki/Introduction.md wiki/Home.md
          mv wiki/Solution_Architecture.md wiki/_Solution_Architecture.md
          mv wiki/Configurations.md wiki/03_Configurations.md
          mv wiki/Explanation.md wiki/04_Explanation.md
          mv wiki/SETUP-and-Installation.md wiki/05_SETUP-and-Installation.md
          mv wiki/FAQ.md wiki/06_FAQ.md
          ls -la wiki  # List files to verify renaming

      - name: Remove Custom Sidebar if Exists
        run: |
          echo "Checking for existing sidebar..."
          if [ -f wiki/_Sidebar.md ]; then
            echo "Removing existing sidebar..."
            rm wiki/_Sidebar.md
          fi

      - name: Commit and Push Changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update wiki content with new file order" || echo "No changes to commit"
          git push
        continue-on-error: true

      - name: List files in wiki directory after push
        run: ls -la wiki
